#!/usr/bin/env bash

if [[ "${FLOWDESK_ENV_LOADED:-0}" == "1" ]]; then
  return 0 2>/dev/null || exit 0
fi

FLOWDESK_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FLOWDESK_ENV_FILE="${FLOWDESK_ENV_FILE:-$FLOWDESK_ROOT_DIR/.env}"

if [[ -f "$FLOWDESK_ENV_FILE" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$FLOWDESK_ENV_FILE"
  set +a
fi

export FLOWDESK_ROOT_DIR
export FLOWDESK_ENV_FILE
export FLOWDESK_GATEWAY_HOST="${FLOWDESK_GATEWAY_HOST:-0.0.0.0}"
export FLOWDESK_GATEWAY_PORT="${FLOWDESK_GATEWAY_PORT:-8080}"
export FLOWDESK_PUBLIC_ORIGIN="${FLOWDESK_PUBLIC_ORIGIN:-http://127.0.0.1:${FLOWDESK_GATEWAY_PORT}}"

export FLOWDESK_FRONTEND_HOST="${FLOWDESK_FRONTEND_HOST:-0.0.0.0}"
export FLOWDESK_FRONTEND_PORT="${FLOWDESK_FRONTEND_PORT:-5173}"
export FLOWDESK_FRONTEND_URL="${FLOWDESK_FRONTEND_URL:-http://127.0.0.1:${FLOWDESK_FRONTEND_PORT}}"

export FLOWDESK_BACKEND_HOST="${FLOWDESK_BACKEND_HOST:-0.0.0.0}"
export FLOWDESK_BACKEND_PORT="${FLOWDESK_BACKEND_PORT:-8000}"
export FLOWDESK_BACKEND_URL="${FLOWDESK_BACKEND_URL:-http://127.0.0.1:${FLOWDESK_BACKEND_PORT}}"

export VITE_API_BASE_URL="${VITE_API_BASE_URL:-/}"

export DB_SERVER="${DB_SERVER:-127.0.0.1}"
export DB_PORT="${DB_PORT:-5432}"
export DB_DATABASE="${DB_DATABASE:-flowdesk}"
export DB_USERNAME="${DB_USERNAME:-postgres}"
export DB_PASSWORD="${DB_PASSWORD:-postgres}"
export SECRET_KEY="${SECRET_KEY:-change-me-before-sharing}"
export ACCESS_TOKEN_EXPIRE_MINUTES="${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"

export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export FLOWDESK_ENV_LOADED=1
